import "../scss/main.scss"
import '../style/components/rbt-token.css';
import ThemeProvider from "@/providers/ThemeProvider";
import AuthProvider from "@/providers/AuthProvider";
import Header from "@/components/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",    
};

export default function RootLayout({ children }) {
    
    return (
        <html lang="en" >
            <body>
                <AuthProvider>
                    <ThemeProvider>
                        <Header />
                        <div className="container position-relative" style={{marginTop: "80px"}}>
                            {children}
                        </div>
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
